<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container62ZfxHb\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container62ZfxHb/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container62ZfxHb.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container62ZfxHb\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container62ZfxHb\App_KernelDevDebugContainer([
    'container.build_hash' => '62ZfxHb',
    'container.build_id' => '5f04e1d2',
    'container.build_time' => 1579782778,
], __DIR__.\DIRECTORY_SEPARATOR.'Container62ZfxHb');
